name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
      - name: Build and publish .NET WASM app
        run: dotnet publish ResxEditor/ResxEditor.csproj -c:Release -p:GHPages=true -o out --nologo
      - name: Change base adress
        run: sed -i 's/<base href="\/" \/>/<base href="\/ResxEditor\/" \/>/g' ./out/wwwroot/index.html && cat ./out/wwwroot/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
